title: Settings
data:
  site_name: 'Recoded Thoughts'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/jason_tame'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/jasontame'
      icon: site/social-icons/github.svg
