title: Settings
data:
  site_name: 'Jason Tame'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/jason_tame'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/jasontame'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:hello@jasontame.dev'
      icon: null
